import { Prisma, prisma } from "@repo/db";
import type { SymbolKind } from "@repo/shared";

/**
 * Phase 04 prompt 4, sub-task 4.1: batched `CodeSymbol` persistence. The `*.repository.ts`
 * suffix is required by ESLint Rule B (phase-00 §3) — this is the only file in
 * `apps/worker` that may import `@repo/db`'s Prisma-backed exports for this table.
 *
 * Follows `repository-file.repository.ts`'s established pattern almost exactly: multi-row
 * `INSERT` via `$executeRaw`, every value bound through `Prisma.sql`/`Prisma.join` — never
 * string-interpolated (`plan.md` §35.11) — batched sequentially (never in parallel, to
 * avoid self-inflicted connection-pool exhaustion; see that file's own note).
 *
 * ## Plain `INSERT`, not upsert
 *
 * `repository-file.repository.ts` upserts because a `RepositoryFile` row's identity
 * (`repositoryId`, `path`) is stable across re-indexes and its `id` must survive so
 * foreign keys (this table's own `fileId`) keep pointing at the same row. `CodeSymbol` has
 * no such continuity requirement: prompt-1 §2.5's idempotency model is full replacement
 * scoped to the repository — {@link deleteByRepository} runs before this module's insert
 * on every (re-)index, so there is never an existing row for a fresh insert to conflict
 * with. A plain `INSERT` is both simpler and cheaper than an upsert that can never
 * exercise its own `ON CONFLICT` branch.
 *
 * ## `id` is generated by the caller, not this module
 *
 * Unlike `repository-file.repository.ts` (which generates `id` internally because nothing
 * downstream needs it back), `graph-builder.ts`'s pass 1 needs every symbol's id *before*
 * insertion — to build the in-memory `Map<name, SymbolId[]>` name index and to let pass 2
 * point `CodeDependency` edges at symbols that were never re-read from Postgres. Generating
 * ids here and handing them back would just be a round trip pass 1 already avoids by
 * construction, so {@link CodeSymbolInsertInput.id} is a required field the caller
 * populates with `randomUUID()` itself (the same reasoning `repository-file.repository.ts`
 * gives for why `id` has no database-level default: `schema.prisma`'s `@default(uuid())`
 * is Prisma-client-side codegen, not a Postgres `DEFAULT`).
 */

export interface CodeSymbolInsertInput {
  id: string;
  repositoryId: string;
  fileId: string;
  name: string;
  kind: SymbolKind;
  startLine: number;
  endLine: number;
  isExported: boolean;
  isDefault: boolean;
  signature: string | null;
  docComment: string | null;
  parentSymbolId: string | null;
  complexity: number;
  commitSha: string;
}

/** `plan.md` §4 Technical Requirements / phase-04 §4: batch size 1,000. */
export const CODE_SYMBOL_BATCH_SIZE = 1000;

/**
 * Inserts `symbols` in batches of {@link CODE_SYMBOL_BATCH_SIZE}, sequentially — the
 * driver-adapter connection pool is shared with every other query this Inngest step's
 * surrounding function might make (`repository-file.repository.ts`'s own note on
 * self-inflicted pool exhaustion applies identically here).
 */
export async function insertCodeSymbols(
  symbols: readonly CodeSymbolInsertInput[],
): Promise<void> {
  for (
    let offset = 0;
    offset < symbols.length;
    offset += CODE_SYMBOL_BATCH_SIZE
  ) {
    const batch = symbols.slice(offset, offset + CODE_SYMBOL_BATCH_SIZE);
    await insertBatch(batch);
  }
}

async function insertBatch(
  batch: readonly CodeSymbolInsertInput[],
): Promise<void> {
  if (batch.length === 0) return;

  const rows = Prisma.join(
    batch.map(
      (s) =>
        Prisma.sql`(
          ${s.id},
          ${s.repositoryId},
          ${s.fileId},
          ${s.name},
          ${s.kind},
          ${s.startLine},
          ${s.endLine},
          ${s.isExported},
          ${s.isDefault},
          ${s.signature},
          ${s.docComment},
          ${s.parentSymbolId},
          ${s.complexity},
          ${s.commitSha}
        )`,
    ),
  );

  await prisma.$executeRaw`
    INSERT INTO "CodeSymbol" (
      "id", "repositoryId", "fileId", "name", "kind", "startLine", "endLine",
      "isExported", "isDefault", "signature", "docComment", "parentSymbolId",
      "complexity", "commitSha"
    )
    VALUES ${rows}
  `;
}

/**
 * Deletes every `CodeSymbol` row for `repositoryId` — the symbol half of prompt-1 §2.5's
 * full-replace idempotency model. `graph-builder.ts` calls this (via its own pass-1
 * entry point) **before** {@link
 * "./code-dependency.repository.js".deleteByRepository | code-dependency's own delete} in
 * the *insert* direction is reversed for *delete*: edges are deleted before symbols (see
 * that module's own header) because `CodeDependency` has no foreign key to `CodeSymbol`
 * — deleting symbols first would leave dangling `toSymbolId`/`fromSymbolId` values on
 * still-live edge rows, whereas deleting edges first and symbols second never does.
 */
export async function deleteCodeSymbolsByRepository(
  repositoryId: string,
): Promise<number> {
  const result = await prisma.codeSymbol.deleteMany({
    where: { repositoryId },
  });
  return result.count;
}
